version: '3.8'
services:
  postgres:
    image: postgres:latest
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    command: -p 5432

  app:
    container_name: app_resume
    hostname: app_resume
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - docker.env
    #    link local changes to container for continuous development
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    command: gunicorn resume.wsgi:application --bind 0.0.0.0:8000

  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    #  until stopped manually nginx will work
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_data:
    