# Generated by Django 4.2.7 on 2023-11-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='parameters',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Parameters'),
        ),
    ]
