# Generated by Django 4.2.7 on 2023-11-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_generalsetting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='parameters',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Parameters'),
        ),
    ]
