# Generated by Django 4.2.7 on 2023-11-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_generalsetting_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='parameters',
            field=models.CharField(blank=True, default='', max_length=10000, null=True, verbose_name='Parameters'),
        ),
    ]
