# Generated by Django 4.2.7 on 2023-11-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_generalsetting_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Description')),
                ('field', models.ImageField(blank=True, default='', null=True, upload_to='media/', verbose_name='Image')),
            ],
        ),
    ]
