# Generated by Django 4.2.7 on 2023-11-30 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_imagesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagesetting',
            options={'ordering': ('name',), 'verbose_name': 'Image Setting', 'verbose_name_plural': 'Image Settings'},
        ),
        migrations.RemoveField(
            model_name='imagesetting',
            name='field',
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='imagesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
