# Generated by Django 4.2.7 on 2023-11-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_skillmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('company_name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Company Name')),
                ('job_title', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Job Title')),
                ('job_location', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Job Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Experience Setting',
                'verbose_name_plural': 'Experience Settings',
                'ordering': ('start_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='skillmodel',
            options={'ordering': ('order',), 'verbose_name': 'Skill Setting', 'verbose_name_plural': 'Skill Settings'},
        ),
    ]
