# Generated by Django 4.2.7 on 2023-11-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_experiencemodel_alter_skillmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('school_name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='School Name')),
                ('major_title', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Major Title')),
                ('school_location', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='School Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
            ],
            options={
                'verbose_name': 'Education Setting',
                'verbose_name_plural': 'Education Settings',
                'ordering': ('start_date',),
            },
        ),
    ]
