# Generated by Django 4.2.7 on 2023-11-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_socialmediamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediamodel',
            name='url',
            field=models.URLField(blank=True, default='', max_length=256, null=True, verbose_name='URL'),
        ),
    ]
