# Generated by Django 4.2.7 on 2023-11-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_socialmediamodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('name', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Name')),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='documents/', verbose_name='File')),
                ('button_text', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Button Text')),
            ],
            options={
                'verbose_name': 'Document Setting',
                'verbose_name_plural': 'Document Settings',
                'ordering': ('order',),
            },
        ),
    ]
