# Generated by Django 4.2.7 on 2023-11-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_documentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='slug_name',
            field=models.SlugField(blank=True, default='', max_length=256, null=True, verbose_name='Slug Name'),
        ),
    ]
