# Generated by Django 4.2.7 on 2023-11-30 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_documentmodel_name_documentmodel_slug_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmodel',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
