# Generated by Django 4.2.7 on 2023-12-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_slug_name_documentmodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsetting',
            old_name='site_title',
            new_name='name',
        ),
    ]
