# Generated by Django 4.2.7 on 2023-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_site_title_generalsetting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='name',
            field=models.TextField(blank=True, default='', help_text='Site name', null=True, verbose_name='Name'),
        ),
    ]
