# Generated by Django 4.2.7 on 2023-12-07 16:34

from django.db import migrations, models
import resume.custom_storages


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_generalsetting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='file',
            field=models.FileField(blank=True, default='', null=True, storage=resume.custom_storages.DocumentStorage(), upload_to='', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='imagesetting',
            name='file',
            field=models.ImageField(blank=True, default='', null=True, storage=resume.custom_storages.ImageStorage(), upload_to='', verbose_name='Image'),
        ),
    ]
