# Generated by Django 4.2.7 on 2023-12-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', max_length=255, null=True, verbose_name='Email')),
                ('subject', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Subject')),
                ('message', models.TextField(blank=True, default='', null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Messages',
                'verbose_name_plural': 'Messages',
                'ordering': ('-created_at',),
            },
        ),
    ]
