# This workflow will deploy code to server on push to main or releases branches

name: Deploy to Server
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/**'

# takes secrets veriables
env:
  SSH_HOST: ${{ secrets.SERVER_HOST_NAME }}
  SSH_PORT: 22
  SSH_USERNAME: ${{ secrets.SERVER_USER_NAME }}
  SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: $SSH_HOST
          port: $SSH_PORT
          username: $SSH_USERNAME
          password: $SSH_PASSWORD
          key: $SSH_PRIVATE_KEY
          script: |
            cd /home/django-resume
            git pull
            docker compose -f docker-compose.yml up --build -d